version: "3.8"

services:

  backend_test:
    build:
      context: ../
      dockerfile: docker/Dockerfile_python.test
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db_test:3306/${DB_DATABASE} # Construct database URL
      - SECRET_KEY=${SECRET_KEY}
      - ENV=test
      - DEBUG=${DEBUG}
    volumes:
      - ../backend/app:/app  # Für Entwicklung
      - ../backend/tests:/tests  # Für Entwicklung
      - ../.cache:/root/.cache
    command: ["sh", "-c", "sleep 5 && while true; do pytest /tests --html=report.html --self-contained-html; sleep 15; done"]
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] # Assumes /health endpoint
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network_unittest

volumes:
  consciousfit_data_test:

networks:
  app-network_unittest:
    driver: bridge
